#!/bin/bash

##----------------------- Start job description -----------------------

#SBATCH --partition=standard
#SBATCH --job-name=msd_mmc_315K_0-500ns_anal
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=m.cores@alumnos.upm.es

##----------------------- End job description ------------------------

module load apps/2021
module load OpenMPI/4.1.4-GCC-12.2.0
module load GROMACS/2021.5-foss-2021b

export GMX_MAXBACKUP=-1

echo "GROMACS VERSION USED FOR ANALYSIS:"
gmx --version

# creates mmc_315K_0-500ns.xtc containing both the initial run and the 500 ns extension; GROMACS sorts frames by time and handles overlaps
gmx trjcat -f mmc_315K.xtc mmc_315K.part0003.xtc -o mmc_315K_0-500ns.xtc

# Now compute MSD using that group (assume it is group 2 in index.ndx)
# MSD: answer both prompts with group 2, then terminate selection with 0 or empty
printf "2\n" | gmx msd -f mmc_315K_0-500ns.xtc -s mmc_315K.tpr -n index.ndx -o msd_mmc_315K_0-500ns.xvg
