#!/bin/bash

##----------------------- Start job description -----------------------

#SBATCH --partition=standard
#SBATCH --job-name=mmc_4265_325K_anal
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mcores@alumnos.upm.es

##----------------------- End job description ------------------------

module load apps/2021
module load OpenMPI/4.1.4-GCC-12.2.0
module load GROMACS/2021.5-foss-2021b

export GMX_MAXBACKUP=-1

echo "GROMACS VERSION USED FOR ANALYSIS:"
gmx --version

printf "2\n" | gmx msd -f mmc_4265_325K.xtc -s mmc_4265_325K.tpr -n index.ndx -o msd_mmc_4265_325K.xvg
