#!/bin/bash

##----------------------- Start job description -----------------------

#SBATCH --partition=standard
#SBATCH --job-name=mmc_64_325K
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=user@domain.com

##----------------------- End job description ------------------------

module load apps/2021
module load OpenMPI/4.1.4-GCC-12.2.0
module load GROMACS/2021.5-foss-2021b

export GMX_MAXBACKUP=-1
#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# 1) Energy minimization
gmx grompp -f ../mdp/minim.mdp -c solvated.gro -p topol.top -o em.tpr -maxwarn 1
mpirun gmx_mpi mdrun -v -deffnm em

# 2) NVT equilibration
gmx grompp -f ../mdp/nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 1
mpirun gmx_mpi mdrun -deffnm nvt

# 3) NPT equilibration
gmx grompp -f ../mdp/npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -maxwarn 1
mpirun gmx_mpi mdrun -deffnm npt

# 4) Production at 325 K
# Output name: mmc_64_325K
gmx grompp -f ../mdp/md.mdp -c npt.gro -t npt.cpt -p topol.top -o mmc_64_325K.tpr -maxwarn 1
mpirun gmx_mpi mdrun -deffnm mmc_64_325K
