#!/bin/bash

##----------------------- Start job description -----------------------

#SBATCH --partition=standard
#SBATCH --job-name=136_mmc_anal
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=user@institution.org

##----------------------- End job description ------------------------

module load apps/2021
module load OpenMPI/4.1.4-GCC-12.2.0
module load GROMACS/2021.5-foss-2021b

export GMX_MAXBACKUP=-1

echo "GROMACS VERSION USED FOR ANALYSIS:"
gmx --version

# 1) Energy minimization: potential energy
printf "10\n0\n" | gmx energy -f em.edr -o potential.xvg

# 2) NVT equilibration: temperature
printf "14\n0\n" | gmx energy -f nvt.edr -o temperature.xvg

# 3) NPT equilibration: pressure and density
printf "16\n0\n" | gmx energy -f npt.edr -o pressure.xvg
printf "22\n0\n" | gmx energy -f npt.edr -o density.xvg

# 4) MSD analysis of MMC
printf "2\nq\n" | gmx make_ndx -f mmc_136_325K.tpr -o index.ndx

# Compute MSD
printf "2\n" | gmx msd -f mmc_136_325K.xtc -s mmc_136_325K.tpr -n index.ndx -o msd_mmc_136_325K.xvg