#!/usr/bin/env bash
set -euo pipefail

# Build DPPC + MMC systems using precise water insertion to avoid oversolvation.
#
# Strategy:
# 1) Calculate exactly how many water molecules to add so that after replacing
#    ~17.5 waters per MMC, we still have >= 30 waters/DPPC.
# 2) Extract a single SOL molecule to act as an insertion template.
# 3) Expand the box Z-height to create voids, and insert EXACTLY the required waters.
# 4) Insert MMC by replacing SOL.
#
# Usage:
#   bash ./build_dppc_mmc_hydrated_cases.sh 32 50 64 100

COUNTS=("$@")
if [ "${#COUNTS[@]}" -eq 0 ]; then
  COUNTS=(32 50 64 100)
fi

ITERATIONS=(i1)
INPUT_GRO="dppc_325K_1bar.part0011.gro"
BASE_TOPOL="topol.top"
MMC_GRO="../mitomycin_c/mmc.gro"
BASE_SEED=325
MAIL_USER="user@institution.org"

MIN_WATER_PER_DPPC="${MIN_WATER_PER_DPPC:-30}"
REPLACE_PER_MMC="${REPLACE_PER_MMC:-21}"
RESIDUE_NAME="${RESIDUE_NAME:-DPPC}"

if [ ! -f "$INPUT_GRO" ]; then echo "Input GRO not found: $INPUT_GRO"; exit 1; fi
if [ ! -f "$BASE_TOPOL" ]; then echo "Base topology not found: $BASE_TOPOL"; exit 1; fi
if [ ! -f "$MMC_GRO" ]; then echo "MMC GRO not found: $MMC_GRO"; exit 1; fi

BASE_DPPC_COUNT=$(awk '/^DPPC[[:space:]]+[0-9]+/ {print $2; exit}' "$BASE_TOPOL")
BASE_SOL_COUNT=$(awk '/^SOL[[:space:]]+[0-9]+/ {print $2; exit}' "$BASE_TOPOL")

BASE_LX=$(awk 'END{print $1}' "$INPUT_GRO")
BASE_LY=$(awk 'END{print $2}' "$INPUT_GRO")
BASE_LZ=$(awk 'END{print $3}' "$INPUT_GRO")

cat << 'PYEOF' > .tmp_helpers.py
import sys, math
from pathlib import Path

def target_sol(dppc_count, min_water):
    print(math.ceil(dppc_count * min_water))

def calc_added(base_sol, min_post_sol, replace_rate, n_mmc, area):
    required_pre_sol = min_post_sol + replace_rate * n_mmc
    added = max(0.0, required_pre_sol - base_sol)
    added = int(math.ceil(added))
    # Actual volume of SPC water is ~0.03 nm^3. Use 0.035 nm^3 to guarantee fully empty space
    extra_lz = (added * 0.035) / area if area > 0 else 0.0
    print(f"{added} {extra_lz:.6f}")

def extract_water(in_gro, out_gro):
    lines = Path(in_gro).read_text().splitlines()
    sol_idx = next(i for i, l in enumerate(lines) if "SOL" in l)
    out = ["One water", "3", lines[sol_idx], lines[sol_idx+1], lines[sol_idx+2], "   1.0000   1.0000   1.0000"]
    Path(out_gro).write_text("\n".join(out) + "\n")

def count_sol(in_gro):
    lines = Path(in_gro).read_text().splitlines()
    natoms = int(lines[1].strip())
    seen = set()
    count = 0
    for line in lines[2:2 + natoms]:
        ri = int(line[:5])
        rn = line[5:10].strip()
        if (ri, rn) not in seen:
            seen.add((ri, rn))
            if rn == "SOL": count += 1
    print(count)

def merge_gro(gro1, gro2, out_gro):
    lines1 = Path(gro1).read_text().splitlines()
    lines2 = Path(gro2).read_text().splitlines()
    n1 = int(lines1[1].strip())
    n2 = int(lines2[1].strip())
    out = [lines1[0], str(n1+n2)]
    out.extend(lines1[2:2+n1])
    out.extend(lines2[2:2+n2])
    out.append(lines1[-1])
    Path(out_gro).write_text("\n".join(out) + "\n")

cmd = sys.argv[1]
if cmd == "target": target_sol(int(sys.argv[2]), float(sys.argv[3]))
elif cmd == "added": calc_added(float(sys.argv[2]), float(sys.argv[3]), float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6]))
elif cmd == "water": extract_water(sys.argv[2], sys.argv[3])
elif cmd == "count": count_sol(sys.argv[2])
elif cmd == "merge": merge_gro(sys.argv[2], sys.argv[3], sys.argv[4])
PYEOF

MIN_SOL_POST=$(python3 .tmp_helpers.py target "$BASE_DPPC_COUNT" "$MIN_WATER_PER_DPPC")
BASE_AREA=$(echo "$BASE_LX * $BASE_LY" | bc -l)

ONE_WATER_GRO=".tmp_1water.gro"
python3 .tmp_helpers.py water "$INPUT_GRO" "$ONE_WATER_GRO"

write_topol() {
  local out_path="$1"
  local n="$2"
  local sol_count="$3"
  cat > "${out_path}" <<EOF
; Topology for DPPC + MMC membrane system
; Generated by build_dppc_mmc_hydrated_cases.sh

#include "../../gromos53a6_lipid.ff/forcefield.itp"
#include "../../dppc.itp"
#include "../../gromos53a6_lipid.ff/spc.itp"
#include "../../gromos53a6_lipid.ff/ions.itp"
#include "../../../mitomycin_c/mmc.itp"

[ system ]
; Name

${BASE_DPPC_COUNT} DPPC bilayer + ${n} MMC in water

[ molecules ]
; Compound        #mols
DPPC              ${BASE_DPPC_COUNT}
SOL               ${sol_count}
X2IT               ${n}
EOF
}

write_run_script() {
  local out_path="$1"
  local n="$2"
  local mail_user="$3"
  cat > "${out_path}" <<EOF
#!/bin/bash
#SBATCH --partition=standard
#SBATCH --job-name=dppc_${n}_mmc_325K
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=${mail_user}

module load apps/2021
module load OpenMPI/4.1.4-GCC-12.2.0
module load GROMACS/2021.5-foss-2021b
export GMX_MAXBACKUP=-1

gmx grompp -f ../../mdp/minim.mdp -c solvated.gro -p topol.top -o em.tpr -maxwarn 1
mpirun gmx_mpi mdrun -v -deffnm em
gmx grompp -f ../../mdp/nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 1
mpirun gmx_mpi mdrun -deffnm nvt
gmx grompp -f ../../mdp/npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -maxwarn 1
mpirun gmx_mpi mdrun -deffnm npt
gmx grompp -f ../../mdp/md.mdp -c npt.gro -t npt.cpt -p topol.top -o dppc_${n}_mmc_325K.tpr -maxwarn 1
mpirun gmx_mpi mdrun -deffnm dppc_${n}_mmc_325K
EOF
}

write_analysis_script() {
  local out_path="$1"
  local n="$2"
  local mail_user="$3"
  cat > "${out_path}" <<EOF
#!/bin/bash
#SBATCH --partition=standard
#SBATCH --job-name=${n}_mmc_anal
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=${mail_user}

module load apps/2021
module load OpenMPI/4.1.4-GCC-12.2.0
module load GROMACS/2021.5-foss-2021b
export GMX_MAXBACKUP=-1

echo "GROMACS VERSION USED FOR ANALYSIS:"
gmx --version
printf "10\\n0\\n" | gmx energy -f em.edr -o potential.xvg
printf "14\\n0\\n" | gmx energy -f nvt.edr -o temperature.xvg
printf "16\\n0\\n" | gmx energy -f npt.edr -o pressure.xvg
printf "22\\n0\\n" | gmx energy -f npt.edr -o density.xvg
printf "2\\q\\n" | gmx make_ndx -f dppc_${n}_mmc_325K.tpr -o index.ndx
printf "2\\n" | gmx msd -f dppc_${n}_mmc_325K.xtc -s dppc_${n}_mmc_325K.tpr -n index.ndx -o msd_mmc_${n}_325K.xvg
EOF
}

write_submit_script() {
  local iteration="$1"
  shift
  local script_counts=("$@")
  local counts_string="${script_counts[*]}"
  local submit_script="submit_all_${iteration}.sh"
  cat > "$submit_script" <<EOF
#!/bin/bash
COUNTS="${counts_string}"
for N in \$(echo \$COUNTS); do
    DIR="\${N}_mmc/${iteration}"
    SCRIPT="run_\${N}_mmc.script"
    if [ ! -d "\$DIR" ] || [ ! -f "\$DIR/\$SCRIPT" ]; then continue; fi
    echo "[SUBMIT] \$DIR/\$SCRIPT"
    (cd "\$DIR" && sbatch "\$SCRIPT")
done
EOF
}

echo "[INFO] Exact-Hydration build settings"
echo "  Base DPPC count: ${BASE_DPPC_COUNT}"
echo "  Base SOL count: ${BASE_SOL_COUNT}"
echo "  Hydration target: >= ${MIN_SOL_POST} SOL post-insertion (${MIN_WATER_PER_DPPC} waters/DPPC)"

for N in "${COUNTS[@]}"; do
  CASE_DIR="${N}_mmc"
  mkdir -p "$CASE_DIR"

  ADDED_VARS=$(python3 .tmp_helpers.py added "$BASE_SOL_COUNT" "$MIN_SOL_POST" "$REPLACE_PER_MMC" "$N" "$BASE_AREA")
  ADDED_WATER=$(echo "$ADDED_VARS" | awk '{print $1}')
  EXTRA_LZ=$(echo "$ADDED_VARS" | awk '{print $2}')
  NEW_LZ=$(echo "$BASE_LZ + $EXTRA_LZ" | bc -l)

  for idx in "${!ITERATIONS[@]}"; do
    iteration="${ITERATIONS[$idx]}"
    seed=$((BASE_SEED + idx + N))
    ITER_DIR="${CASE_DIR}/${iteration}"
    mkdir -p "$ITER_DIR"

    EXPANDED_GRO="${ITER_DIR}/expanded.gro"
    PRE_GRO="${ITER_DIR}/presolv.gro"
    OUT_GRO="${ITER_DIR}/solvated.gro"

    echo "[BUILD] ${CASE_DIR}/${iteration} (target ${MIN_SOL_POST} SOL)"
    
    if [ "$ADDED_WATER" -gt 0 ]; then
      echo "  - adding $ADDED_WATER SOL (expanding Lz $BASE_LZ -> $NEW_LZ)"
      # 1. Expand the DPPC box in Z, creating void space from BASE_LZ to NEW_LZ
      gmx editconf -f "$INPUT_GRO" -o "$EXPANDED_GRO" -c -box "$BASE_LX" "$BASE_LY" "$NEW_LZ" >/dev/null 2>&1
      
      # 2. Build a completely independent block of pure water to fit in that void
      # We make the Z box slightly smaller than the void (-0.1) to avoid periodic boundary clashes upon merge
      WATER_BOX_LZ=$(echo "$EXTRA_LZ - 0.1" | bc -l)
      gmx insert-molecules -ci "$ONE_WATER_GRO" -nmol "$ADDED_WATER" -box "$BASE_LX" "$BASE_LY" "$WATER_BOX_LZ" -seed "$seed" -try 10000 -o "pure_water_block.gro" >/dev/null 2>&1
      
      # 3. Translate this pure water block physically up in the Z axis to sit on top of the original DPPC membrane limits
      gmx editconf -f "pure_water_block.gro" -translate 0 0 "$BASE_LZ" -o "pure_water_block_trans.gro" >/dev/null 2>&1
      
      # 4. Merge them mathematically at the coordinates level so they never overlap inherently
      python3 .tmp_helpers.py merge "$EXPANDED_GRO" "pure_water_block_trans.gro" "$PRE_GRO"
      rm -f pure_water_block.gro pure_water_block_trans.gro
    else
      echo "  - no extra water needed"
      cp "$INPUT_GRO" "$PRE_GRO"
    fi

    echo "  - inserting $N MMC (replacing SOL)"
    gmx insert-molecules -f "$PRE_GRO" -ci "$MMC_GRO" -nmol "$N" -replace "resname SOL" -try 10000 -seed "$seed" -o "$OUT_GRO" >/dev/null 2>&1

    FINAL_SOL=$(python3 .tmp_helpers.py count "$OUT_GRO")
    
    if [ "$FINAL_SOL" -lt "$MIN_SOL_POST" ]; then
      echo "[ERROR] Final SOL (${FINAL_SOL}) < required (${MIN_SOL_POST}). Increase REPLACE_PER_MMC."
      exit 1
    fi
    
    echo "  - success: ${FINAL_SOL} SOL remaining"
    
    write_topol "${ITER_DIR}/topol.top" "$N" "$FINAL_SOL"
    write_run_script "${ITER_DIR}/run_${N}_mmc.script" "$N" "$MAIL_USER"
    write_analysis_script "${ITER_DIR}/run_${N}_mmc_anal.script" "$N" "$MAIL_USER"
    chmod +x "${ITER_DIR}/run_${N}_mmc.script" "${ITER_DIR}/run_${N}_mmc_anal.script"
  done
done

write_submit_script "i0" "${COUNTs[@]}"
rm -f .tmp_helpers.py "$ONE_WATER_GRO"
echo "Build complete."
