#!/usr/bin/env bash
set -euo pipefail

# Build DPPC + MMC systems by replacing SOL molecules using gmx insert-molecules.
# Usage:
#   ./build_dppc_mmc_cases.sh                # builds 1,2,4 by default
#   ./build_dppc_mmc_cases.sh 1 2 4 8 16

COUNTS=("$@")
if [ "${#COUNTS[@]}" -eq 0 ]; then
  COUNTS=(1 2 4)
fi

INPUT_GRO="dppc_325K_1bar.part0011.gro"
MMC_GRO="../mitomycin_c/mmc.gro"
DEFAULT_SEED=325

if [ ! -f "$INPUT_GRO" ]; then
  echo "Input GRO not found: $INPUT_GRO"
  exit 1
fi

if [ ! -f "$MMC_GRO" ]; then
  echo "MMC GRO not found: $MMC_GRO"
  exit 1
fi

for N in "${COUNTS[@]}"; do
  CASE_DIR="${N}_mmc"
  OUT_GRO="${CASE_DIR}/solvated.gro"

  mkdir -p "$CASE_DIR"
  echo "[BUILD] ${CASE_DIR}: inserting ${N} X2IT molecules by replacing SOL"

  gmx insert-molecules \
    -f "$INPUT_GRO" \
    -ci "$MMC_GRO" \
    -nmol "$N" \
    -replace "resname SOL" \
    -try 5000 \
    -seed "$DEFAULT_SEED" \
    -o "$OUT_GRO"

  SOL_COUNT=$(python3 - "$OUT_GRO" <<'PY'
from pathlib import Path
import sys
p = Path(sys.argv[1])
lines = p.read_text().splitlines()
natoms = int(lines[1].strip())
atoms = lines[2:2+natoms]
seen = set()
count = 0
for l in atoms:
    resid = int(l[:5])
    resname = l[5:10].strip()
    key = (resid, resname)
    if key in seen:
        continue
    seen.add(key)
    if resname == "SOL":
        count += 1
print(count)
PY
)

  cat > "${CASE_DIR}/topol.top" <<EOF
; Topology for DPPC + MMC membrane system
; Generated by build_dppc_mmc_cases.sh

#include "../../gromos53a6_lipid.ff/forcefield.itp"
#include "../../dppc.itp"
#include "../../../mitomycin_c/mmc.itp"

#include "../../gromos53a6_lipid.ff/spc.itp"
#include "../../gromos53a6_lipid.ff/ions.itp"

[ system ]
; Name
256 DPPC bilayer + ${N} X2IT in water

[ molecules ]
; Compound        #mols
DPPC              256
X2IT              ${N}
SOL               ${SOL_COUNT}
EOF

  echo "  - Wrote ${CASE_DIR}/topol.top (SOL=${SOL_COUNT})"
  echo "  - System GRO: ${OUT_GRO}"
done

echo "Build complete."
