#!/bin/bash
set -e

concentrations=(4 8 12 16)
# box_size is determined by editconf -d 2

# Optional first arg selects concentration root inside concentration_study.
# Examples:
#   ./setup_systems.sh .      -> concentration_study/8_mmc, 16_mmc, ...
#   ./setup_systems.sh 300K   -> concentration_study/300K/8_mmc, ...
target_root="${1:-.}"

# Deterministic insertion by default; override with INSERT_SEED env var.
insert_seed="${INSERT_SEED:-20260331}"

# Ensure we are in the correct directory (concentration_study)
cd "$(dirname "$0")"

for n in "${concentrations[@]}"; do
    folder="${target_root}/${n}_mmc"
    folder="${folder#./}"
    echo "Setting up ${folder}..."

    if [ ! -d "$folder" ]; then
        echo "Warning: Folder $folder does not exist."
        continue
    fi

    cd "$folder"

    # 1. Cleanup old files
    rm -f *.ff *.mdp *.itp box_mmc.gro boxed.gro solvated.gro

    # 2. Generate topol.top
    if [ "${target_root}" = "." ]; then
        ff_prefix="../../mitomycin_c"
    else
        ff_prefix="../../../mitomycin_c"
    fi

    cat <<EOF > topol.top
; Topology for Mitomycin C concentration study
; Generated by setup_systems.sh

; Include the GROMOS 54A7 force field parameters.
#include "${ff_prefix}/gromos54a7_atb.ff/forcefield.itp"

; Include the specific topology file for your molecule.
#include "${ff_prefix}/mmc.itp"

; Include the water topology (SPC is the standard water model for GROMOS)
#include "${ff_prefix}/gromos54a7_atb.ff/spc.itp"

; Include topology for standard ions
#include "${ff_prefix}/gromos54a7_atb.ff/ions.itp"

[ system ]
; Name
$n X2IT Molecules Solvated in SPC Water

[ molecules ]
; Compound        #mols
X2IT              $n
EOF
    echo "  - Generated topol.top"

    # 3. Create Box and Insert Molecules
    mmc_gro="${ff_prefix}/mmc.gro"

    # A. Create the base box with 1 molecule (centered, 2nm buffer)
    # This replicates the box setup from the single-molecule temperature study
    echo "  - Executing: gmx editconf -f $mmc_gro -o boxed.gro -c -d 2 -bt cubic"
    gmx editconf -f "$mmc_gro" -o boxed.gro -c -d 2 -bt cubic

    # B. Insert the remaining N-1 molecules into the existing box
    if [ -f "boxed.gro" ]; then
        n_insert=$((n - 1))
        
        echo "  - Executing: gmx insert-molecules -f boxed.gro -ci $mmc_gro -nmol $n_insert -seed $insert_seed -o box_mmc.gro"
        gmx insert-molecules -f boxed.gro -ci "$mmc_gro" -nmol $n_insert -seed "$insert_seed" -o box_mmc.gro
        
        # 4. Solvate
        if [ -f "box_mmc.gro" ]; then
            echo "  - Executing: gmx solvate -cp box_mmc.gro -cs spc216.gro -o solvated.gro -p topol.top"
            gmx solvate -cp box_mmc.gro -cs spc216.gro -o solvated.gro -p topol.top
            
            if [ -f "solvated.gro" ]; then
                echo "  - Success: $folder initialized."
            else
                echo "  - Failed to generate solvated.gro for $folder"
            fi
        else
            echo "  - Failed to insert additional molecules for $folder"
        fi
    else
         echo "  - Failed to create base box (boxed.gro) for $folder"
    fi

    cd ..
done

echo "Setup script finished."
